require: rubocop-rails

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Layout/LineLength:
  Max: 80
  IgnoredPatterns: ['\A\s*#']

Style/Documentation:
  Enabled: false 

Rails/FilePath:
  Enabled: false

Metrics/AbcSize:
  Max: 20
  Exclude:
    - 'db/migrate/*.rb'

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*.rb'

Rails/HasAndBelongsToMany:
  Enabled: false

Metrics/BlockLength:
  Max: 75
  Exclude:
    - 'spec/**/*_spec.rb'
